import EnglandRegion from "../constants/EnglandRegion";

const mapping = {
  [EnglandRegion.London]: [
    "City of London",
    "Westminster",
    "Kensington and Chelsea",
    "Hammersmith and Fulham",
    "Wandsworth",
    "Lambeth",
    "Southwark",
    "Tower Hamlets",
    "Hackney",
    "Islington",
    "Camden",
    "Brent",
    "Ealing",
    "Hounslow",
    "Richmond upon Thames",
    "Kingston upon Thames",
    "Merton",
    "Sutton",
    "Croydon",
    "Bromley",
    "Lewisham",
    "Greenwich",
    "Bexley",
    "Havering",
    "Barking and Dagenham",
    "Redbridge",
    "Newham",
    "Waltham Forest",
    "Haringey",
    "Enfield",
    "Barnet",
    "Harrow",
    "Hillingdon",
  ],
  [EnglandRegion.EastMidlands]: [
    "Amber Valley",
    "Ashfield",
    "Bassetlaw",
    "Blaby",
    "Bolsover",
    "Boston",
    "Broxtowe",
    "Charnwood",
    "Chesterfield",
    "Corby",
    "Daventry",
    "Derby",
    "Derbyshire County",
    "Derbyshire Dales",
    "East Lindsey",
    "East Northamptonshire",
    "Erewash",
    "Gedling",
    "Har",
    "High Peak",
    "Hinckley and Bosworth",
    "Kettering",
    "Leicester City",
    "Leicestershire County",
    "Lincoln City",
    "Lincolnshire County",
    "Mansfield",
    "Melton",
    "Newark and Sherwood",
    "North East Derbyshire",
    "North Kesteven",
    "North West Leicestershire",
    "Northampton",
    "Northamptonshire County",
    "Nottingham City",
    "Nottinghamshire County",
    "Oadby and Wigston",
    "PeakNational Park Authority",
    "Rushcliffe",
    "Rutland County",
    "South Derbyshire",
    "South Holland",
    "South Kesteven",
    "South Northamptonshire",
    "Welling",
    "West Lindsey",
  ],
  [EnglandRegion.EastOfEngland]: [],
  [EnglandRegion.NorthEast]: [],
  [EnglandRegion.NorthWest]: [],
  [EnglandRegion.SouthEast]: [],
  [EnglandRegion.SouthWest]: [],
  [EnglandRegion.WestMidlands]: [],
  [EnglandRegion.YorkshireAndTheHumber]: [],
};

export default mapping;
