export const FETCH_COUNTRYWISE_RECORDS_SUCCESS =
  "FETCH_COUNTRYWISE_RECORDS_SUCCESS";
export const FETCH_COUNTRYWISE_RECORDS_ERROR =
  "FETCH_COUNTRYWISE_RECORDS_ERROR";
export const FETCH_COUNTRYWISE_RECORDS = "FETCH_COUNTRYWISE_RECORDS";
export const DAILY_COUNTRYWISE_RECORDS = "DAILY_COUNTRYWISE_RECORDS";
export const FETCH_COUNTRYWISE_DATE = "FETCH_COUNTRYWISE_DATE";

export const FETCH_REGIONWISE_RECORDS_SUCCESS =
  "FETCH_REGIONWISE_RECORDS_SUCCESS";
export const FETCH_REGIONWISE_RECORDS_ERROR = "FETCH_REGIONWISE_RECORDS_ERROR";
export const FETCH_REGIONWISE_RECORDS = "FETCH_REGIONWISE_RECORDS";
export const DAILY_REGIONWISE_RECORDS = "DAILY_REGIONWISE_RECORDS";
export const FETCH_REGIONWISE_DATE = "FETCH_REGIONWISE_DATE";

export const FETCH_LOCAL_AUTHORITY_RECORDS_SUCCESS =
  "FETCH_LOCAL_AUTHORITY_RECORDS_SUCCESS";
export const FETCH_LOCAL_AUTHORITY_RECORDS_ERROR =
  "FETCH_LOCAL_AUTHORITY_RECORDS_ERROR";
export const FETCH_LOCAL_AUTHORITY_RECORDS = "FETCH_LOCAL_AUTHORITY_RECORDS";
export const DAILY_LOCAL_AUTHORITY_RECORDS = "DAILY_LOCAL_AUTHORITY_RECORDS";
export const FETCH_LOCAL_AUTHORITY_DATE = "FETCH_LOCAL_AUTHORITY_DATE";
export const FILTER_LOCAL_AUTHORITY_BY_REGION =
  "FILTER_LOCAL_AUTHORITY_BY_REGION";

export const FETCH_LANDING_RECORDS_SUCCESS = "FETCH_LANDING_RECORDS_SUCCESS";
export const HANDLE_DATE_RANGE_CHANGE = "HANDLE_DATE_RANGE_CHANGE";
